#-------------------------------------------------------------------------
#
# Makefile for backend/embedded
#
# src/backend/embedded/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/embedded
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pgembedded.o

include $(top_srcdir)/src/backend/common.mk
